//ARQUIVO PRINCIPAL
//CONSTANTE EXPRESS RECEBENDO O MODULO DO EXPRESS
const express = require("express");

//CONSTANTE DESESTRUTURADA PARA IMPORTAR ROTAS
const { rotas } = require("../src/router/rotas.js")

//CRIAR UMA APLICACAO A PARTIR DO EXPRESS
const app = express();

//CONTANTE COM O NUMERO DA PORTA
const PORTA = 3000;

//CONFIGURAR TRANSITAÇÃO VIA JSON  INTERMEDIARIO PRA RECONHECER JSON

app.use(express.json());

//CRIACAO DE APLICACAO DAS ROTAS
app.use(rotas);

//CRIACAO DA ROTA COM PARAMETRO ID, POR QUE SE NAO BATER NA ROTA, NAO CHEGA
//NAO PRECISA NEM VERIFICAR, SE TEM ID OU NAO. => O PARAMETRO "id" FAZ PARTE DA ROTA


app.listen(PORTA, () => console.log(`API rodando na porta ${PORTA}!`));
